name: Deploy Nextra to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: write  # Needed to push to gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use the version your project needs

      - name: Install dependencies
        run: npm ci

      - name: Build and export static site
        run: |
          npm run build
          npm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
